### ISSUE TITLE
How to test own code?

### ISSUE THREAD

**Issue by watertrainer** [ActivityWatch/aw-core#96]
I am sorry if there already is an explanation online, I couldn't find anything. How would I compile own code from aw-core, so that a test server would be able to use it, or more spefically, after I run `make build` from aw-server, which should include my aw-core code, where do I find the finished binary/where can I run the compiled code now?

**Comment by ErikBjare** [comment]
See the building from source guide: https://docs.activitywatch.net/en/latest/installing-from-source.html

**Comment by watertrainer** [comment]
First of all, thanks for the quick Answer

I read that guide, but it didn't tell me _where_ to run aw-server or aw-watcher-*. Doing it in the root directory of the repo didn't work,  I did not find anything in the Makefile.

**Comment by johan-bjareholt** [comment]
"it didn't work" isn't enough information for us to help you, please be more specific.

Aw-server and aw-core is built with the popular python build tool poetry as specified in the guide and configured with the project.toml file. Exactly how to change the version of aw-core built with aw-server can be done in multiple ways, but that's more of a python specific question rather than an ActivityWatch question.

**Comment by ErikBjare** [comment]
Once you've built with `make build` they should be available in your virtualenv's PATH.

**Comment by ErikBjare** [comment]
Once you've built with `make build` they should be available in your virtualenv's PATH.

**Comment by watertrainer** [comment]
Ok, thank you for your help. The adding to the PATH was the problem, but running the console as Admin fixed it. 

Thanks for the help, sorry for not being specific enough.
